-- Lab 07: Primary Keys


-- 1. Column-level Primary Key

CREATE TABLE students (
    student_id INTEGER PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(150)
);

\d students

DROP TABLE students;


-- 2. Table-level Primary Key

CREATE TABLE students (
    student_id INTEGER,
    name VARCHAR(100),
    email VARCHAR(150),
    PRIMARY KEY (student_id)
);

\d students

DROP TABLE students;


-- 3. Named Primary Key Constraint

CREATE TABLE students (
    student_id INTEGER,
    name VARCHAR(100),
    email VARCHAR(150),
    CONSTRAINT pk_students PRIMARY KEY (student_id)
);

\d students

DROP TABLE students;


-- 4. Adding Primary Key to an Existing Table

CREATE TABLE students_no_pk (
    student_id INTEGER,
    name VARCHAR(100),
    email VARCHAR(150)
);

\d students_no_pk

ALTER TABLE students_no_pk
ADD CONSTRAINT pk_students PRIMARY KEY (student_id);

\d students_no_pk

DROP TABLE students_no_pk;


-- 5. Single-column Primary Key with SERIAL

CREATE TABLE students (
    student_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE,
    faculty VARCHAR(50)
);

INSERT INTO students (name, email, faculty) VALUES
('Alice Johnson', 'alice@alatoo.edu.kg', 'Computer Science'),
('Bob Smith', 'bob@alatoo.edu.kg', 'Mathematics'),
('Carol Davis', 'carol@alatoo.edu.kg', 'Computer Science');

\d students

SELECT * FROM students;

DROP TABLE students;


-- 6. Composite Primary Key

CREATE TABLE course_enrollments (
    student_id INTEGER,
    course_id INTEGER,
    semester VARCHAR(20),
    enrollment_date DATE DEFAULT CURRENT_DATE,
    grade CHAR(2),
    PRIMARY KEY (student_id, course_id, semester)
);

INSERT INTO course_enrollments
    (student_id, course_id, semester, grade)
VALUES
    (1, 101, '2024-Spring', 'A'),
    (1, 102, '2024-Spring', 'B+'),
    (2, 101, '2024-Spring', 'A-'),
    (1, 101, '2024-Fall', 'A+');

SELECT * FROM course_enrollments;

\d course_enrollments

DROP TABLE course_enrollments;


-- 7. SERIAL

CREATE TABLE products_lab7 (
    product_id SERIAL PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    price DECIMAL(10,2)
);

\d products_lab7

DROP TABLE products_lab7;


-- 8. BIGSERIAL

CREATE TABLE transactions (
    transaction_id BIGSERIAL PRIMARY KEY,
    amount DECIMAL(15,2),
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

\d transactions

DROP TABLE transactions;


-- 9. GENERATED ALWAYS AS IDENTITY

CREATE TABLE orders_lab7 (
    order_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(100),
    order_date DATE DEFAULT CURRENT_DATE
);

\d orders_lab7

DROP TABLE orders_lab7;


-- 10. GENERATED BY DEFAULT AS IDENTITY

CREATE TABLE customers_lab7 (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(100),
    email VARCHAR(150)
);

\d customers_lab7

INSERT INTO customers_lab7
    (customer_id, customer_name, email)
VALUES
    (1000, 'VIP Customer', 'vip@example.com');

SELECT * FROM customers_lab7;

DROP TABLE customers_lab7;


-- 11. Primary Key Constraints

CREATE TABLE departments_lab7 (
    dept_id INTEGER PRIMARY KEY,
    dep_name VARCHAR(100)
);

-- First row is inserted successfully
INSERT INTO departments_lab7
VALUES
    (1, 'Computer Science');

-- Duplicate primary key test
INSERT INTO departments_lab7
VALUES
    (1, 'Mathematics');

-- NULL primary key test
INSERT INTO departments_lab7
VALUES
    (NULL, 'Physics');

DROP TABLE departments_lab7;
